// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAabXzD_v5swR12sEp2ZjSfQzK2RXFiujM',
    appId: '1:1069755549925:web:ea5339c0f1fc845a466c0c',
    messagingSenderId: '1069755549925',
    projectId: 'kampoeng-rusuh',
    authDomain: 'kampoeng-rusuh.firebaseapp.com',
    databaseURL: 'https://kampoeng-rusuh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kampoeng-rusuh.firebasestorage.app',
    measurementId: 'G-XNDGTJYFPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAwcY6jmSgYgZSJQqiLLDg1s8x_G0mtLc',
    appId: '1:1069755549925:android:542858a6923df649466c0c',
    messagingSenderId: '1069755549925',
    projectId: 'kampoeng-rusuh',
    databaseURL: 'https://kampoeng-rusuh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kampoeng-rusuh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-hD1in7lSKNOv_k8lUvfJdtXAI_3-_iQ',
    appId: '1:1069755549925:ios:e7dd812facc4d47c466c0c',
    messagingSenderId: '1069755549925',
    projectId: 'kampoeng-rusuh',
    databaseURL: 'https://kampoeng-rusuh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kampoeng-rusuh.firebasestorage.app',
    iosBundleId: 'com.example.kampoengRusuh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-hD1in7lSKNOv_k8lUvfJdtXAI_3-_iQ',
    appId: '1:1069755549925:ios:e7dd812facc4d47c466c0c',
    messagingSenderId: '1069755549925',
    projectId: 'kampoeng-rusuh',
    databaseURL: 'https://kampoeng-rusuh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kampoeng-rusuh.firebasestorage.app',
    iosBundleId: 'com.example.kampoengRusuh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAabXzD_v5swR12sEp2ZjSfQzK2RXFiujM',
    appId: '1:1069755549925:web:2ad274856856a7e0466c0c',
    messagingSenderId: '1069755549925',
    projectId: 'kampoeng-rusuh',
    authDomain: 'kampoeng-rusuh.firebaseapp.com',
    databaseURL: 'https://kampoeng-rusuh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kampoeng-rusuh.firebasestorage.app',
    measurementId: 'G-TJK2J1SV4D',
  );

}